# Generated by Django 5.0.6 on 2024-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.TextField(choices=[('M', 'Maintenance'), ('O', 'On loan'), ('A', 'Available'), ('R', 'Reserved')], max_length=1),
        ),
    ]
