# Generated by Django 5.0.6 on 2024-08-15 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A set of tasks grouped together', max_length=50, verbose_name='group_name')),
                ('owner', models.ForeignKey(help_text='the user crating this set of tasks.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('importance', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], help_text='assuming the importance can go from 1 to 5. The larger the number, the more important the task is')),
                ('status', models.CharField(choices=[('N', 'New'), ('I', 'In progress'), ('D', 'Done')], help_text='the status of the task', max_length=1)),
                ('description', models.TextField(help_text='a description of the task, can be of any length', null=True)),
                ('group', models.ForeignKey(help_text='the id of the group the given task belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
        ),
    ]
