# Generated by Django 5.0.6 on 2024-09-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyauthcode',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spotifyauthcode',
            name='client_secret',
            field=models.CharField(max_length=100),
        ),
    ]
