# Generated by Django 5.0.6 on 2024-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('client_id', 'client_secret')},
            },
        ),
    ]
