# Generated by Django 5.0.6 on 2024-09-11 10:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_musicroom_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='musicroom',
            name='code',
            field=models.CharField(default=api.models._generate_random_room_code, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
