# Generated by Django 5.0.6 on 2024-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.TextField(max_length=30)),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisine', models.TextField(max_length=20)),
            ],
        ),
    ]
