# Generated by Django 5.0.6 on 2024-07-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='_id',
            new_name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.cuisinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuIncludeDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ManyToManyField(to='menu.dish')),
                ('menu_id', models.ManyToManyField(to='menu.menu')),
            ],
        ),
    ]
