# Generated by Django 5.0.6 on 2024-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.TextField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
